global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sequencer'
    honor_timestamps: true
    metrics_path: /debug/metrics/prometheus
    # scheme: http
    static_configs:
      - targets: ["sequencer:6070"]

  - job_name: "eigenda_proxy"
    static_configs:
      - targets: ["eigenda-proxy:7300"]
