name: CI
run-name: CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Temporarily disabling this until a fix is pushed upstream
        # pos: [pos, no-pos]
        l3node: [l3node, l3node-token-6, no-l3node]
        tokenbridge: [tokenbridge, no-tokenbridge]
        eigenda: [eigenda, no-eigenda]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Startup Nitro testnode
        env:
          EIGENDA_SIGNER_PRIVATE_KEY: ${{ secrets.EIGENDA_SIGNER_PRIVATE_KEY }}
        ## add this into run CMD when prysm patch is applied upstream
        ## $ {{ matrix.pos == 'pos' && '--pos' || '' }}
        run: EIGENDA_SIGNER_PRIVATE_KEY=$EIGENDA_SIGNER_PRIVATE_KEY ${{ github.workspace }}/.github/workflows/testnode.bash --init-force ${{ (matrix.l3node == 'l3node' && '--l3node') || (matrix.l3node == 'l3node-token-6' && '--l3node --l3-fee-token --l3-token-bridge --l3-fee-token-decimals 6') || '' }} ${{ matrix.tokenbridge == 'tokenbridge' && '--tokenbridge' || '--no-tokenbridge' }} --no-simple --detach ${{matrix.eigenda == 'eigenda' && '--eigenda' || ''}}
