name: Build and publish forkdiff github-pages
permissions:
    contents: read
    pages: write
    id-token: write
on:
  push:
    branches:
      - main
      - epociask--feat-fork-diff
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000  # make sure to fetch the old commit we diff against

      - name: Build forkdiff
        uses: "docker://protolambda/forkdiff:0.1.0"
        with:
          args: -repo=/github/workspace -fork=/github/workspace/fork.yaml -out=/github/workspace/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
            source: ./
            destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4